"""empty message

Revision ID: e47fb2d3a756
Revises: 
Create Date: 2017-06-30 17:30:56.066364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47fb2d3a756'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modelfiles', sa.Column('friendly_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modelfiles', 'friendly_name')
    # ### end Alembic commands ###
